# name: Create IAM Users

# on:
#   push:
#     branches:
#       - main

# jobs:
#   create-users:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Setup AWS CLI
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1

#       - name: Run deploy script
#         run: |
#           chmod +x scripts/deploy.sh
#           ./scripts/deploy.sh "new-username" # Replace with dynamic logic if needed
